apiVersion: apps/v1
kind: DaemonSet

Metadata:
  name: nginx-ds
spec:

 selector:
   matchLabels:
     app: ds-web
 template:
   metadata:
     labels:
       app: ds-web
   spec:
     containers:
     - name: nginx
       image: nginx
       imagePullPolicy: IfNotPresent

